checks:
    python:
        code_rating: true
        duplicate_code: true

filter:
    dependency_paths:
        - lib/

build:
    environment:
        python: '3.6'
        postgresql: false
        redis: false

    dependencies:
        override:
            # Project depends
            - pip install aiodns cchardet ujson aiohttp asyncio beautifulsoup4
            # Coverage depends
            - pip install pylint>=1.8.1 mypy>=0.580 lxml coverage pytest pytest-cov

    project_setup:
        before:
            - command: git clone https://github.com/ShyPixie/stlib
            - command: cd stlib/src/steam_api
            - command: image_id=$(docker create shypixie/steamworks_sdk)
            - command: docker cp $image_id:steamworks_sdk - > steamworks.tar.gz
            - command: tar xfv steamworks.tar.gz
            - command: cd ../..
            - command: python setup.py build
            - command: python setup.py install
            - command: cd ..
        override:
            - command: python setup.py build
            - command: python setup.py install

    tests:
        override:
            - py-scrutinizer-run
            - command: pylint-run stlib --rcfile=pylintrc
            - command: mypy steam-tools-ng.py --linecoverage-report mypy.report
            - command: echo -n "!coverage.py: This is a private format, don't read it directly!">.mypy_coverage
            - command: cat mypy.report/coverage.json>>.mypy_coverage
              coverage:
                  file: '.mypy_coverage'
                  format: 'py-cc'
