name: Coverage
on:
  push:
    branches:
     - master
    tags-ignore:
      - '**'

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    name: Python ${{ matrix.python-version }} coverage
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          pip install -r dev-requirements.txt
          pytest --cov=./ --cov-report=xml
      - uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          verbose: true
