name: Deploy

on:
  release:
    types: [published]

jobs:
  winget:
    name: Publish
    runs-on: windows-latest
    steps:
      - name: Submit
        run: /
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $installerUrl = $github.release.assets | Where-Object -Property name -match 'steam-tools-ng-setup.exe' | Select -ExpandProperty browser_download_url -First 1
          $versionNumber = $github.release.tag_name -replace ".*v"
          .\wingetcreate.exe update calendulish.SteamToolsNG -s -v $versionNumber -u $installerUrl -t ${{ secrets.STNG_PAT }}
